@server = http://localhost:4004

### Listar Orders
# @name Orders_GET
GET {{server}}/odata/v4/catalog/Orders
Accept: application/json

### Criar Order
# @name Orders_POST
POST {{server}}/odata/v4/catalog/Orders
Content-Type: application/json
Accept: application/json

{
  "CompanyCode": "1000",
  "Supplier": "SUPPLIER_A",
  "Currency": "USD",
  "NetAmount": 5085292.26,
  "Status": "OPEN"
}

### Atualizar Order (PATCH)
# Substitua o caminho pelo ID correto:
# - Numérico:  (1)
# - UUID:      (ID=guid'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx')
# @name Orders_PATCH
PATCH {{server}}/odata/v4/catalog/Orders(c15b535f-3751-4e5f-962d-fb8bce1f5eaa)
Content-Type: application/json
Accept: application/json

{
  "CompanyCode": "1000",
  "Supplier": "SUPPLIER_A",
  "Currency": "USD",
  "NetAmount": 5085292.26,
  "Status": "OPEN"
}

### Deletar Order
# Não envie corpo no DELETE
# @name Orders_DELETE
DELETE {{server}}/odata/v4/catalog/Orders(cb938469-c90e-46d1-bdd1-3e80f190bd41)
Accept: application/json
